vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Move selected line(s) down' })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Move selected line(s) up' })
vim.keymap.set('n', '<leader>f', vim.cmd.Explore, { desc = 'Open file explorer' })
vim.keymap.set('n', '<leader>x', '<cmd>!chmod +x %<CR>', { silent = true, desc = 'Make current file executable' })
vim.keymap.set('n', 'N', 'Nzzzv', { desc = 'Search for previous occurrence' })
vim.keymap.set('n', 'n', 'nzzzv', { desc = 'Search for next occurrence' })
vim.keymap.set('v', '<C-c>', '"+y', { desc = 'Copy to system clipboard' })
